services:
  db:
    image: ghcr.io/postgresml/postgresml:2.7.12
    container_name: keren-ai-db
    command: sudo -u postgresml psql -d postgresml
    tty: true
    stdin_open: true
    volumes:
      - keren_ai_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=postgresml
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal-network

  admin-service:
    build:
      context: .
      dockerfile: admin-service/Dockerfile
    container_name: keren-ai-admin
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_BASE_URL=${GROQ_BASE_URL}
      - GROQ_MODEL=${GROQ_MODEL}
      - GROQ_TEMPERATURE=${GROQ_TEMPERATURE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - internal-network

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: keren-ai-auth
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - internal-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: keren-ai-api-gateway
    ports:
      - "4003:4003"
    depends_on:
      - admin-service
      - auth-service
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge

volumes:
  keren_ai_data: